export const SUBJECTS = [
  { id: 1, name: 'Applied Anatomy', edition: 'E5', total: 240, done: 65, accuracy: 72, active: true },
  { id: 2, name: 'Applied Physiology', edition: 'E5', total: 180, done: 0, accuracy: 0, active: false },
  { id: 3, name: 'Biochemistry', edition: 'E4', total: 120, done: 0, accuracy: 0, active: false },
  { id: 4, name: 'Community Health Nursing', edition: 'E5', total: 200, done: 30, accuracy: 55, active: false },
  { id: 5, name: 'Fundamentals of Nursing', edition: 'E5', total: 220, done: 110, accuracy: 80, active: false },
  { id: 6, name: 'Medical-Surgical Nursing', edition: 'E5', total: 320, done: 45, accuracy: 62, active: false },
  { id: 7, name: 'Mental Health Nursing', edition: 'E4', total: 140, done: 0, accuracy: 0, active: false },
  { id: 8, name: 'Obstetric Nursing', edition: 'E5', total: 180, done: 20, accuracy: 68, active: false },
  { id: 9, name: 'Pediatric Nursing', edition: 'E5', total: 160, done: 0, accuracy: 0, active: false },
  { id: 10, name: 'Pharmacology', edition: 'E5', total: 200, done: 80, accuracy: 76, active: false },
]

export const CHAPTERS = [
  { id: 1, name: 'Anatomical Terms', topics: 4, qs: 21, marks: 21, difficulty: 'easy', state: 'unattempted', vid: true },
  { id: 2, name: 'Skeletal System', topics: 6, qs: 30, marks: 30, difficulty: 'moderate', state: 'paused', prog: { done: 14, total: 30 }, vid: true },
  { id: 3, name: 'Muscular System', topics: 5, qs: 25, marks: 25, difficulty: 'moderate', state: 'completed', res: { correct: 18, total: 25, pct: 87, ahead: 87 }, vid: true },
  { id: 4, name: 'Nervous System', topics: 8, qs: 40, marks: 40, difficulty: 'difficult', state: 'unattempted', vid: false },
  { id: 5, name: 'Cardiovascular System', topics: 5, qs: 28, marks: 28, difficulty: 'moderate', state: 'unattempted', vid: true },
  { id: 6, name: 'Respiratory System', topics: 4, qs: 22, marks: 22, difficulty: 'moderate', state: 'unattempted', vid: true },
]

export const TOPICS = [
  { id: 1, name: 'Body Movements & Terminology', qs: 6, pyqs: 2 },
  { id: 2, name: 'Body Planes & Sections', qs: 5, pyqs: 1 },
  { id: 3, name: 'Directional Terminology', qs: 6, pyqs: 3 },
  { id: 4, name: 'Body Cavities', qs: 4, pyqs: 0 },
]

export const QUESTIONS = [
  {
    id: 1,
    topicId: 1,
    topicName: 'Body Movements & Terminology',
    text: 'Which anatomical term describes movement of a limb away from the midline of the body?',
    options: [
      { id: 'a', text: 'Adduction', pct: 18 },
      { id: 'b', text: 'Abduction', pct: 67 },
      { id: 'c', text: 'Flexion', pct: 10 },
      { id: 'd', text: 'Extension', pct: 5 },
    ],
    correct: 'b',
    explanation: 'Abduction refers to the movement of a limb or body part away from the midline of the body. It is the anatomical opposite of adduction, which brings the limb toward the midline. Common examples include raising the arms sideways or spreading the fingers apart.',
    references: "Gray's Anatomy, 41st Edition, Chapter 3 — Movements of Joints",
    learnTopic: 'Body Movements',
    isPYQ: true,
    pyqExam: 'NORCET',
    pyqYear: 2023,
  },
  {
    id: 2,
    topicId: 2,
    topicName: 'Body Planes & Sections',
    text: 'The sagittal plane divides the body into which two sections?',
    options: [
      { id: 'a', text: 'Superior and Inferior halves', pct: 12 },
      { id: 'b', text: 'Anterior and Posterior halves', pct: 23 },
      { id: 'c', text: 'Left and Right halves', pct: 58 },
      { id: 'd', text: 'Medial and Lateral sections', pct: 7 },
    ],
    correct: 'c',
    explanation: 'The sagittal plane is a vertical plane that runs front to back, dividing the body into left and right sections. The midsagittal (median) plane divides the body into equal left and right halves. The parasagittal plane divides the body into unequal left and right portions.',
    references: 'Clinical Anatomy by Regions, 9th Edition — Body Planes',
    learnTopic: 'Body Planes',
    isPYQ: false,
    pyqExam: null,
    pyqYear: null,
  },
  {
    id: 3,
    topicId: 3,
    topicName: 'Directional Terminology',
    text: 'In anatomical terminology, which term correctly describes the position of the heart relative to the stomach?',
    options: [
      { id: 'a', text: 'Inferior to the stomach', pct: 15 },
      { id: 'b', text: 'Posterior to the stomach', pct: 20 },
      { id: 'c', text: 'Superior to the stomach', pct: 55 },
      { id: 'd', text: 'Lateral to the stomach', pct: 10 },
    ],
    correct: 'c',
    explanation: "The heart is located superior (above) to the stomach in standard anatomical position. The heart lies in the thoracic cavity while the stomach is in the abdominal cavity. 'Superior' in anatomical terminology refers to a position closer to the head.",
    references: "Moore's Clinically Oriented Anatomy, 8th Edition",
    learnTopic: 'Directional Terms',
    isPYQ: true,
    pyqExam: 'AIIMS',
    pyqYear: 2022,
  },
  {
    id: 4,
    topicId: 1,
    topicName: 'Body Movements & Terminology',
    text: 'In standard anatomical position, the palms of the hands face which direction?',
    options: [
      { id: 'a', text: 'Posteriorly (backward)', pct: 8 },
      { id: 'b', text: 'Anteriorly (forward)', pct: 72 },
      { id: 'c', text: 'Medially (inward)', pct: 14 },
      { id: 'd', text: 'Laterally (outward)', pct: 6 },
    ],
    correct: 'b',
    explanation: 'In standard anatomical position, the body stands erect with feet together, arms at the sides, and palms facing anteriorly (forward). This is the reference position from which all anatomical descriptions and directional terms are derived.',
    references: "Gray's Anatomy, 41st Edition — Anatomical Position",
    learnTopic: 'Anatomical Position',
    isPYQ: true,
    pyqExam: 'NORCET',
    pyqYear: 2024,
  },
  {
    id: 5,
    topicId: 3,
    topicName: 'Directional Terminology',
    text: 'Which term refers to the front surface of the body in standard anatomical position?',
    options: [
      { id: 'a', text: 'Dorsal', pct: 18 },
      { id: 'b', text: 'Posterior', pct: 22 },
      { id: 'c', text: 'Anterior / Ventral', pct: 52 },
      { id: 'd', text: 'Inferior', pct: 8 },
    ],
    correct: 'c',
    explanation: "The anterior (or ventral) surface refers to the front of the body. Posterior (or dorsal) refers to the back. These paired terms are used extensively in clinical anatomy — for example, the anterior cruciate ligament (ACL) is located on the front side of the knee joint.",
    references: 'Principles of Anatomy and Physiology, 15th Edition',
    learnTopic: 'Directional Terms',
    isPYQ: true,
    pyqExam: 'NORCET',
    pyqYear: 2023,
  },
  {
    id: 6,
    topicId: 4,
    topicName: 'Body Cavities',
    text: 'Which body cavity houses both the heart and lungs?',
    options: [
      { id: 'a', text: 'Abdominal cavity', pct: 10 },
      { id: 'b', text: 'Pelvic cavity', pct: 5 },
      { id: 'c', text: 'Thoracic cavity', pct: 78 },
      { id: 'd', text: 'Cranial cavity', pct: 7 },
    ],
    correct: 'c',
    explanation: 'The thoracic cavity is located within the chest and is bounded by the rib cage, sternum, thoracic vertebrae, and diaphragm. It contains the heart (in the pericardial cavity), both lungs (in pleural cavities), esophagus, trachea, and major blood vessels.',
    references: "Gray's Anatomy, 41st Edition — Body Cavities",
    learnTopic: 'Body Cavities',
    isPYQ: false,
    pyqExam: null,
    pyqYear: null,
  },
]

export const TOPPER = {
  name: 'Priya Sharma',
  rank: 'AIR 1',
  exam: 'NORCET 2024',
  quote: 'I solved 1,200+ QBank questions in 90 days. Reviewing wrong answers daily was the real game-changer.',
  strategy: 'QBank every morning, videos every evening. No shortcuts.',
}

export const SAVE_TAGS = [
  { id: 'wrong', label: 'Got it Wrong', color: '#791F1F', bg: '#FCEBEB', border: '#F09595' },
  { id: 'important', label: 'Important', color: '#3C3489', bg: '#EEEDFE', border: '#AFA9EC' },
  { id: 'revision', label: 'Needs Revision', color: '#633806', bg: '#FAEEDA', border: '#FAC775' },
  { id: 'tricky', label: 'Tricky Concept', color: '#3B6D11', bg: '#EAF3DE', border: '#97C459' },
]
